var namespacecore =
[
    [ "CircularDependencyException", "classcore_1_1CircularDependencyException.html", null ],
    [ "ConnectedParameterException", "classcore_1_1ConnectedParameterException.html", null ],
    [ "ConnectionException", "classcore_1_1ConnectionException.html", null ],
    [ "CoreException", "classcore_1_1CoreException.html", null ],
    [ "DeserializationException", "classcore_1_1DeserializationException.html", null ],
    [ "DuplicateNodeIdException", "classcore_1_1DuplicateNodeIdException.html", null ],
    [ "EmptyGraphException", "classcore_1_1EmptyGraphException.html", null ],
    [ "FileAccessException", "classcore_1_1FileAccessException.html", null ],
    [ "FileNotFoundException", "classcore_1_1FileNotFoundException.html", null ],
    [ "FunctionInputNode", "classcore_1_1FunctionInputNode.html", "classcore_1_1FunctionInputNode" ],
    [ "FunctionNode", "classcore_1_1FunctionNode.html", "classcore_1_1FunctionNode" ],
    [ "FunctionNodeException", "classcore_1_1FunctionNodeException.html", null ],
    [ "FunctionOutputNode", "classcore_1_1FunctionOutputNode.html", "classcore_1_1FunctionOutputNode" ],
    [ "FunctionParameter", "structcore_1_1FunctionParameter.html", null ],
    [ "Graph", "classcore_1_1Graph.html", "classcore_1_1Graph" ],
    [ "GraphException", "classcore_1_1GraphException.html", null ],
    [ "GraphModificationException", "classcore_1_1GraphModificationException.html", null ],
    [ "IncompatiblePinTypesException", "classcore_1_1IncompatiblePinTypesException.html", null ],
    [ "InvalidJsonSchemaException", "classcore_1_1InvalidJsonSchemaException.html", null ],
    [ "InvalidNodeKindException", "classcore_1_1InvalidNodeKindException.html", null ],
    [ "InvalidParameterException", "classcore_1_1InvalidParameterException.html", null ],
    [ "InvalidPinIndexException", "classcore_1_1InvalidPinIndexException.html", null ],
    [ "InvalidReturnTypeException", "classcore_1_1InvalidReturnTypeException.html", null ],
    [ "LiteralNode", "classcore_1_1LiteralNode.html", "classcore_1_1LiteralNode" ],
    [ "NodeBase", "classcore_1_1NodeBase.html", "classcore_1_1NodeBase" ],
    [ "NodeNotFoundException", "classcore_1_1NodeNotFoundException.html", null ],
    [ "OperatorNode", "classcore_1_1OperatorNode.html", "classcore_1_1OperatorNode" ],
    [ "ParameterNotFoundException", "classcore_1_1ParameterNotFoundException.html", null ],
    [ "PinAlreadyConnectedException", "classcore_1_1PinAlreadyConnectedException.html", null ],
    [ "PinNotConnectedException", "classcore_1_1PinNotConnectedException.html", null ],
    [ "PinStillConnectedException", "classcore_1_1PinStillConnectedException.html", null ],
    [ "SelfConnectionException", "classcore_1_1SelfConnectionException.html", null ],
    [ "SerializationException", "classcore_1_1SerializationException.html", null ],
    [ "VariableNode", "classcore_1_1VariableNode.html", "classcore_1_1VariableNode" ]
];