import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  aboutSidebar: [{type: 'autogenerated', dirName: 'about'}],
  userSidebar: [{type: 'autogenerated', dirName: 'user'}],
  devSidebar: [{type: 'autogenerated', dirName: 'dev'}],
};

export default sidebars;
