import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  aboutSidebar: [{type: 'autogenerated', dirName: 'about'}],
  userSidebar: [{type: 'autogenerated', dirName: 'user'}],
  devSidebar: [
    'dev/intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'dev/getting-started/installation',
        'dev/getting-started/configuration',
      ]
    },
    {
      type: 'category',
      label: 'Architecture',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Core',
          link: {
            type: 'doc',
            id: 'dev/architecture/core/intro'
          },
          items: [
            'dev/architecture/core/graph',
            'dev/architecture/core/node',
          ]
        },
        {
          type: 'category',
          label: 'Core C Nodes',
          link: {
            type: 'doc',
            id: 'dev/architecture/nodes/intro'
          },
          items: [
            'dev/architecture/nodes/literal-node',
            'dev/architecture/nodes/variable-node',
            'dev/architecture/nodes/function-node',
            'dev/architecture/nodes/function-input-node',
            'dev/architecture/nodes/function-output-node',
            'dev/architecture/nodes/operator-node',
            'dev/architecture/nodes/condition-node',
            'dev/architecture/nodes/loop-node',
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'To be sorted',
      items: [
        'dev/to-sort/cmake-tool',
        'dev/to-sort/nebula-format',
        'dev/to-sort/exceptions',
      ]
    },
  ],
};

export default sidebars;
