import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  aboutSidebar: [{type: 'autogenerated', dirName: 'about'}],
  userSidebar: [{type: 'autogenerated', dirName: 'user'}],
  devSidebar: [
    'dev/intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'dev/getting-started/installation',
        'dev/getting-started/configuration',
      ]
    },
    {
      type: 'category',
      label: 'Architecture',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Core',
          link: {
            type: 'doc',
            id: 'dev/architecture/core/intro'
          },
          items: [
            
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'To be sorted',
      items: [
        'dev/to-sort/cmake-tool',
        'dev/to-sort/nebula-format',
      ]
    },
  ],
};

export default sidebars;
